/**@jsx h*/
window.questions = (h, Fragment) => [
  {
    question:
      "Find the sum of all even Fibonacci numbers where the Fibonacci number is less than 4 million.",
    hint: ""
  },
  {
    question: () =>
      h(
        Fragment,
        null,
        "Find a*b*c where a",
        h("sup", null, "2"),
        "+b",
        h("sup", null, "2"),
        "=c",
        h("sup", null, "2"),
        "and a + b + c = 1000."
      ),
    hint: ""
  },
  {
    question: "Find the first triangle number which has 450 or more factors.",
    hint:
      "The sequence of triangle numbers is generated by adding the natural numbers. The fourth triangle number would be 1 + 2 + 3 + 4 = 10"
  },
  {
    question: "Find the sum of all prime numbers below 950,976.",
    hint: ""
  },
  {
    question:
      "Find the number under 1 million which produces the longest Collatz sequence. ",
    hint:
      "For a number n, a collatz sequence is given by n/2 if n is even and 3n+1 if n is odd. For example, Collatz sequence for n=10 would be 10, 5, 16, 8, 4, 2, 1 producing 7 terms. The sequence ends when you reach 1"
  },
  {
    question: () =>
      h(
        Fragment,
        null,
        "Find the sum of square of the digits of 2",
        h("sup", null, "15000."),
        h(
          "div",
          {
            class: "or-btn"
          },
          "OR"
        ),
        h(
          "div",
          null,
          "Find the largest palindrome made from the product of two 3-digit numbers."
        )
      ),
    hint: ""
  },
  {
    question: () =>
      h(
        Fragment,
        null,
        "Find the last 20 digits of the sequence, 1",
        h("sup", null, "1"),
        " + 2",
        h("sup", null, "2"),
        " + 3",
        h("sup", null, "3"),
        "\u2026... + 1000",
        h("sup", null, "1000"),
        ".",
        h(
          "div",
          {
            class: "or-btn"
          },
          "OR"
        ),
        h(
          "div",
          null,
          "What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"
        )
      )
  },
  {
    question:
      "How many starting numbers under 100,000 get 89 as a term in a square digit chain?",
    hint:
      "A square digit chain is formed by adding the squares of the individual digits of the number. For example, square digit chain of 44 is (16 + 16) -> 32 (9 + 4)-> 13 (1 + 9) -> 10 (1 +0) -> 1"
  },
  {
    question: () =>
      h(
        Fragment,
        null,
        "Find the sum of last 651 digits of 4",
        h("sup", null, "32", h("sup", null, "3")),
        h(
          "div",
          {
            class: "or-btn"
          },
          "OR"
        ),
        h("div", null, "Find the 1000th prime number.")
      ),
    hint: ""
  },
  {
    question: "Find the sum of all perfect square even numbers below 10,000.",
    hint: ""
  }
];
